// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

public interface CreateWatcherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.CreateWatcherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>bool recursive = 2 [json_name = "recursive"];</code>
   * @return The recursive.
   */
  boolean getRecursive();
}
