// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

public interface CreateWatcherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.CreateWatcherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
   * @return The watcherId.
   */
  java.lang.String getWatcherId();
  /**
   * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
   * @return The bytes for watcherId.
   */
  com.google.protobuf.ByteString
      getWatcherIdBytes();
}
