// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

public interface EntryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.EntryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.filesystem.FileType type = 2 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.filesystem.FileType type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  com.sandbox.filesystem.FileType getType();

  /**
   * <code>string path = 3 [json_name = "path"];</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 3 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>int64 size = 4 [json_name = "size"];</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>uint32 mode = 5 [json_name = "mode"];</code>
   * @return The mode.
   */
  int getMode();

  /**
   * <code>string permissions = 6 [json_name = "permissions"];</code>
   * @return The permissions.
   */
  java.lang.String getPermissions();
  /**
   * <code>string permissions = 6 [json_name = "permissions"];</code>
   * @return The bytes for permissions.
   */
  com.google.protobuf.ByteString
      getPermissionsBytes();

  /**
   * <code>string owner = 7 [json_name = "owner"];</code>
   * @return The owner.
   */
  java.lang.String getOwner();
  /**
   * <code>string owner = 7 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <code>string group = 8 [json_name = "group"];</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 8 [json_name = "group"];</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>.google.protobuf.Timestamp modified_time = 9 [json_name = "modifiedTime"];</code>
   * @return Whether the modifiedTime field is set.
   */
  boolean hasModifiedTime();
  /**
   * <code>.google.protobuf.Timestamp modified_time = 9 [json_name = "modifiedTime"];</code>
   * @return The modifiedTime.
   */
  com.google.protobuf.Timestamp getModifiedTime();
  /**
   * <code>.google.protobuf.Timestamp modified_time = 9 [json_name = "modifiedTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifiedTimeOrBuilder();

  /**
   * <pre>
   * If the entry is a symlink, this field contains the target of the symlink.
   * </pre>
   *
   * <code>optional string symlink_target = 10 [json_name = "symlinkTarget"];</code>
   * @return Whether the symlinkTarget field is set.
   */
  boolean hasSymlinkTarget();
  /**
   * <pre>
   * If the entry is a symlink, this field contains the target of the symlink.
   * </pre>
   *
   * <code>optional string symlink_target = 10 [json_name = "symlinkTarget"];</code>
   * @return The symlinkTarget.
   */
  java.lang.String getSymlinkTarget();
  /**
   * <pre>
   * If the entry is a symlink, this field contains the target of the symlink.
   * </pre>
   *
   * <code>optional string symlink_target = 10 [json_name = "symlinkTarget"];</code>
   * @return The bytes for symlinkTarget.
   */
  com.google.protobuf.ByteString
      getSymlinkTargetBytes();
}
