// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

public interface FilesystemEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.FilesystemEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.filesystem.EventType type = 2 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.filesystem.EventType type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  com.sandbox.filesystem.EventType getType();
}
