// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

public interface ListDirResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.ListDirResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .filesystem.EntryInfo entries = 1 [json_name = "entries"];</code>
   */
  java.util.List<com.sandbox.filesystem.EntryInfo> 
      getEntriesList();
  /**
   * <code>repeated .filesystem.EntryInfo entries = 1 [json_name = "entries"];</code>
   */
  com.sandbox.filesystem.EntryInfo getEntries(int index);
  /**
   * <code>repeated .filesystem.EntryInfo entries = 1 [json_name = "entries"];</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .filesystem.EntryInfo entries = 1 [json_name = "entries"];</code>
   */
  java.util.List<? extends com.sandbox.filesystem.EntryInfoOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .filesystem.EntryInfo entries = 1 [json_name = "entries"];</code>
   */
  com.sandbox.filesystem.EntryInfoOrBuilder getEntriesOrBuilder(
      int index);
}
