// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

public interface ListDirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.ListDirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>uint32 depth = 2 [json_name = "depth"];</code>
   * @return The depth.
   */
  int getDepth();
}
