// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

public interface MakeDirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.MakeDirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
