// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

/**
 * Protobuf type {@code filesystem.RemoveWatcherRequest}
 */
public final class RemoveWatcherRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:filesystem.RemoveWatcherRequest)
    RemoveWatcherRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RemoveWatcherRequest.newBuilder() to construct.
  private RemoveWatcherRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemoveWatcherRequest() {
    watcherId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RemoveWatcherRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_RemoveWatcherRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_RemoveWatcherRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sandbox.filesystem.RemoveWatcherRequest.class, com.sandbox.filesystem.RemoveWatcherRequest.Builder.class);
  }

  public static final int WATCHER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object watcherId_ = "";
  /**
   * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
   * @return The watcherId.
   */
  @java.lang.Override
  public java.lang.String getWatcherId() {
    java.lang.Object ref = watcherId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      watcherId_ = s;
      return s;
    }
  }
  /**
   * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
   * @return The bytes for watcherId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWatcherIdBytes() {
    java.lang.Object ref = watcherId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      watcherId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(watcherId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, watcherId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(watcherId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, watcherId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sandbox.filesystem.RemoveWatcherRequest)) {
      return super.equals(obj);
    }
    com.sandbox.filesystem.RemoveWatcherRequest other = (com.sandbox.filesystem.RemoveWatcherRequest) obj;

    if (!getWatcherId()
        .equals(other.getWatcherId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WATCHER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWatcherId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.RemoveWatcherRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sandbox.filesystem.RemoveWatcherRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code filesystem.RemoveWatcherRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:filesystem.RemoveWatcherRequest)
      com.sandbox.filesystem.RemoveWatcherRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_RemoveWatcherRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_RemoveWatcherRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.filesystem.RemoveWatcherRequest.class, com.sandbox.filesystem.RemoveWatcherRequest.Builder.class);
    }

    // Construct using com.sandbox.filesystem.RemoveWatcherRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      watcherId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_RemoveWatcherRequest_descriptor;
    }

    @java.lang.Override
    public com.sandbox.filesystem.RemoveWatcherRequest getDefaultInstanceForType() {
      return com.sandbox.filesystem.RemoveWatcherRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sandbox.filesystem.RemoveWatcherRequest build() {
      com.sandbox.filesystem.RemoveWatcherRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sandbox.filesystem.RemoveWatcherRequest buildPartial() {
      com.sandbox.filesystem.RemoveWatcherRequest result = new com.sandbox.filesystem.RemoveWatcherRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sandbox.filesystem.RemoveWatcherRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.watcherId_ = watcherId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sandbox.filesystem.RemoveWatcherRequest) {
        return mergeFrom((com.sandbox.filesystem.RemoveWatcherRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sandbox.filesystem.RemoveWatcherRequest other) {
      if (other == com.sandbox.filesystem.RemoveWatcherRequest.getDefaultInstance()) return this;
      if (!other.getWatcherId().isEmpty()) {
        watcherId_ = other.watcherId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              watcherId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object watcherId_ = "";
    /**
     * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
     * @return The watcherId.
     */
    public java.lang.String getWatcherId() {
      java.lang.Object ref = watcherId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        watcherId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
     * @return The bytes for watcherId.
     */
    public com.google.protobuf.ByteString
        getWatcherIdBytes() {
      java.lang.Object ref = watcherId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        watcherId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
     * @param value The watcherId to set.
     * @return This builder for chaining.
     */
    public Builder setWatcherId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      watcherId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWatcherId() {
      watcherId_ = getDefaultInstance().getWatcherId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string watcher_id = 1 [json_name = "watcherId"];</code>
     * @param value The bytes for watcherId to set.
     * @return This builder for chaining.
     */
    public Builder setWatcherIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      watcherId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:filesystem.RemoveWatcherRequest)
  }

  // @@protoc_insertion_point(class_scope:filesystem.RemoveWatcherRequest)
  private static final com.sandbox.filesystem.RemoveWatcherRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sandbox.filesystem.RemoveWatcherRequest();
  }

  public static com.sandbox.filesystem.RemoveWatcherRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemoveWatcherRequest>
      PARSER = new com.google.protobuf.AbstractParser<RemoveWatcherRequest>() {
    @java.lang.Override
    public RemoveWatcherRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RemoveWatcherRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemoveWatcherRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sandbox.filesystem.RemoveWatcherRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

