// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

public interface RemoveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.RemoveResponse)
    com.google.protobuf.MessageOrBuilder {
}
