// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

/**
 * Protobuf type {@code filesystem.StatResponse}
 */
public final class StatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:filesystem.StatResponse)
    StatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatResponse.newBuilder() to construct.
  private StatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_StatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_StatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sandbox.filesystem.StatResponse.class, com.sandbox.filesystem.StatResponse.Builder.class);
  }

  public static final int ENTRY_FIELD_NUMBER = 1;
  private com.sandbox.filesystem.EntryInfo entry_;
  /**
   * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
   * @return Whether the entry field is set.
   */
  @java.lang.Override
  public boolean hasEntry() {
    return entry_ != null;
  }
  /**
   * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
   * @return The entry.
   */
  @java.lang.Override
  public com.sandbox.filesystem.EntryInfo getEntry() {
    return entry_ == null ? com.sandbox.filesystem.EntryInfo.getDefaultInstance() : entry_;
  }
  /**
   * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
   */
  @java.lang.Override
  public com.sandbox.filesystem.EntryInfoOrBuilder getEntryOrBuilder() {
    return entry_ == null ? com.sandbox.filesystem.EntryInfo.getDefaultInstance() : entry_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (entry_ != null) {
      output.writeMessage(1, getEntry());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (entry_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEntry());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sandbox.filesystem.StatResponse)) {
      return super.equals(obj);
    }
    com.sandbox.filesystem.StatResponse other = (com.sandbox.filesystem.StatResponse) obj;

    if (hasEntry() != other.hasEntry()) return false;
    if (hasEntry()) {
      if (!getEntry()
          .equals(other.getEntry())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEntry()) {
      hash = (37 * hash) + ENTRY_FIELD_NUMBER;
      hash = (53 * hash) + getEntry().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sandbox.filesystem.StatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.filesystem.StatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.StatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.StatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sandbox.filesystem.StatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code filesystem.StatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:filesystem.StatResponse)
      com.sandbox.filesystem.StatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_StatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_StatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.filesystem.StatResponse.class, com.sandbox.filesystem.StatResponse.Builder.class);
    }

    // Construct using com.sandbox.filesystem.StatResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      entry_ = null;
      if (entryBuilder_ != null) {
        entryBuilder_.dispose();
        entryBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_StatResponse_descriptor;
    }

    @java.lang.Override
    public com.sandbox.filesystem.StatResponse getDefaultInstanceForType() {
      return com.sandbox.filesystem.StatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sandbox.filesystem.StatResponse build() {
      com.sandbox.filesystem.StatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sandbox.filesystem.StatResponse buildPartial() {
      com.sandbox.filesystem.StatResponse result = new com.sandbox.filesystem.StatResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sandbox.filesystem.StatResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.entry_ = entryBuilder_ == null
            ? entry_
            : entryBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sandbox.filesystem.StatResponse) {
        return mergeFrom((com.sandbox.filesystem.StatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sandbox.filesystem.StatResponse other) {
      if (other == com.sandbox.filesystem.StatResponse.getDefaultInstance()) return this;
      if (other.hasEntry()) {
        mergeEntry(other.getEntry());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getEntryFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.sandbox.filesystem.EntryInfo entry_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.filesystem.EntryInfo, com.sandbox.filesystem.EntryInfo.Builder, com.sandbox.filesystem.EntryInfoOrBuilder> entryBuilder_;
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     * @return Whether the entry field is set.
     */
    public boolean hasEntry() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     * @return The entry.
     */
    public com.sandbox.filesystem.EntryInfo getEntry() {
      if (entryBuilder_ == null) {
        return entry_ == null ? com.sandbox.filesystem.EntryInfo.getDefaultInstance() : entry_;
      } else {
        return entryBuilder_.getMessage();
      }
    }
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     */
    public Builder setEntry(com.sandbox.filesystem.EntryInfo value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        entry_ = value;
      } else {
        entryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     */
    public Builder setEntry(
        com.sandbox.filesystem.EntryInfo.Builder builderForValue) {
      if (entryBuilder_ == null) {
        entry_ = builderForValue.build();
      } else {
        entryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     */
    public Builder mergeEntry(com.sandbox.filesystem.EntryInfo value) {
      if (entryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          entry_ != null &&
          entry_ != com.sandbox.filesystem.EntryInfo.getDefaultInstance()) {
          getEntryBuilder().mergeFrom(value);
        } else {
          entry_ = value;
        }
      } else {
        entryBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     */
    public Builder clearEntry() {
      bitField0_ = (bitField0_ & ~0x00000001);
      entry_ = null;
      if (entryBuilder_ != null) {
        entryBuilder_.dispose();
        entryBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     */
    public com.sandbox.filesystem.EntryInfo.Builder getEntryBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getEntryFieldBuilder().getBuilder();
    }
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     */
    public com.sandbox.filesystem.EntryInfoOrBuilder getEntryOrBuilder() {
      if (entryBuilder_ != null) {
        return entryBuilder_.getMessageOrBuilder();
      } else {
        return entry_ == null ?
            com.sandbox.filesystem.EntryInfo.getDefaultInstance() : entry_;
      }
    }
    /**
     * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.filesystem.EntryInfo, com.sandbox.filesystem.EntryInfo.Builder, com.sandbox.filesystem.EntryInfoOrBuilder> 
        getEntryFieldBuilder() {
      if (entryBuilder_ == null) {
        entryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.filesystem.EntryInfo, com.sandbox.filesystem.EntryInfo.Builder, com.sandbox.filesystem.EntryInfoOrBuilder>(
                getEntry(),
                getParentForChildren(),
                isClean());
        entry_ = null;
      }
      return entryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:filesystem.StatResponse)
  }

  // @@protoc_insertion_point(class_scope:filesystem.StatResponse)
  private static final com.sandbox.filesystem.StatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sandbox.filesystem.StatResponse();
  }

  public static com.sandbox.filesystem.StatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatResponse>
      PARSER = new com.google.protobuf.AbstractParser<StatResponse>() {
    @java.lang.Override
    public StatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sandbox.filesystem.StatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

