// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem/filesystem.proto

package com.sandbox.filesystem;

/**
 * Protobuf type {@code filesystem.WatchDirResponse}
 */
public final class WatchDirResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:filesystem.WatchDirResponse)
    WatchDirResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WatchDirResponse.newBuilder() to construct.
  private WatchDirResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WatchDirResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WatchDirResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sandbox.filesystem.WatchDirResponse.class, com.sandbox.filesystem.WatchDirResponse.Builder.class);
  }

  public interface StartEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:filesystem.WatchDirResponse.StartEvent)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code filesystem.WatchDirResponse.StartEvent}
   */
  public static final class StartEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:filesystem.WatchDirResponse.StartEvent)
      StartEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StartEvent.newBuilder() to construct.
    private StartEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StartEvent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StartEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_StartEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_StartEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.filesystem.WatchDirResponse.StartEvent.class, com.sandbox.filesystem.WatchDirResponse.StartEvent.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sandbox.filesystem.WatchDirResponse.StartEvent)) {
        return super.equals(obj);
      }
      com.sandbox.filesystem.WatchDirResponse.StartEvent other = (com.sandbox.filesystem.WatchDirResponse.StartEvent) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.filesystem.WatchDirResponse.StartEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sandbox.filesystem.WatchDirResponse.StartEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code filesystem.WatchDirResponse.StartEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:filesystem.WatchDirResponse.StartEvent)
        com.sandbox.filesystem.WatchDirResponse.StartEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_StartEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_StartEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sandbox.filesystem.WatchDirResponse.StartEvent.class, com.sandbox.filesystem.WatchDirResponse.StartEvent.Builder.class);
      }

      // Construct using com.sandbox.filesystem.WatchDirResponse.StartEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_StartEvent_descriptor;
      }

      @java.lang.Override
      public com.sandbox.filesystem.WatchDirResponse.StartEvent getDefaultInstanceForType() {
        return com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.sandbox.filesystem.WatchDirResponse.StartEvent build() {
        com.sandbox.filesystem.WatchDirResponse.StartEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sandbox.filesystem.WatchDirResponse.StartEvent buildPartial() {
        com.sandbox.filesystem.WatchDirResponse.StartEvent result = new com.sandbox.filesystem.WatchDirResponse.StartEvent(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sandbox.filesystem.WatchDirResponse.StartEvent) {
          return mergeFrom((com.sandbox.filesystem.WatchDirResponse.StartEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sandbox.filesystem.WatchDirResponse.StartEvent other) {
        if (other == com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:filesystem.WatchDirResponse.StartEvent)
    }

    // @@protoc_insertion_point(class_scope:filesystem.WatchDirResponse.StartEvent)
    private static final com.sandbox.filesystem.WatchDirResponse.StartEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sandbox.filesystem.WatchDirResponse.StartEvent();
    }

    public static com.sandbox.filesystem.WatchDirResponse.StartEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StartEvent>
        PARSER = new com.google.protobuf.AbstractParser<StartEvent>() {
      @java.lang.Override
      public StartEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StartEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StartEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse.StartEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeepAliveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:filesystem.WatchDirResponse.KeepAlive)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code filesystem.WatchDirResponse.KeepAlive}
   */
  public static final class KeepAlive extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:filesystem.WatchDirResponse.KeepAlive)
      KeepAliveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KeepAlive.newBuilder() to construct.
    private KeepAlive(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeepAlive() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KeepAlive();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_KeepAlive_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_KeepAlive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.filesystem.WatchDirResponse.KeepAlive.class, com.sandbox.filesystem.WatchDirResponse.KeepAlive.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sandbox.filesystem.WatchDirResponse.KeepAlive)) {
        return super.equals(obj);
      }
      com.sandbox.filesystem.WatchDirResponse.KeepAlive other = (com.sandbox.filesystem.WatchDirResponse.KeepAlive) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sandbox.filesystem.WatchDirResponse.KeepAlive prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code filesystem.WatchDirResponse.KeepAlive}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:filesystem.WatchDirResponse.KeepAlive)
        com.sandbox.filesystem.WatchDirResponse.KeepAliveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_KeepAlive_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_KeepAlive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sandbox.filesystem.WatchDirResponse.KeepAlive.class, com.sandbox.filesystem.WatchDirResponse.KeepAlive.Builder.class);
      }

      // Construct using com.sandbox.filesystem.WatchDirResponse.KeepAlive.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_KeepAlive_descriptor;
      }

      @java.lang.Override
      public com.sandbox.filesystem.WatchDirResponse.KeepAlive getDefaultInstanceForType() {
        return com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance();
      }

      @java.lang.Override
      public com.sandbox.filesystem.WatchDirResponse.KeepAlive build() {
        com.sandbox.filesystem.WatchDirResponse.KeepAlive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sandbox.filesystem.WatchDirResponse.KeepAlive buildPartial() {
        com.sandbox.filesystem.WatchDirResponse.KeepAlive result = new com.sandbox.filesystem.WatchDirResponse.KeepAlive(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sandbox.filesystem.WatchDirResponse.KeepAlive) {
          return mergeFrom((com.sandbox.filesystem.WatchDirResponse.KeepAlive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sandbox.filesystem.WatchDirResponse.KeepAlive other) {
        if (other == com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:filesystem.WatchDirResponse.KeepAlive)
    }

    // @@protoc_insertion_point(class_scope:filesystem.WatchDirResponse.KeepAlive)
    private static final com.sandbox.filesystem.WatchDirResponse.KeepAlive DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sandbox.filesystem.WatchDirResponse.KeepAlive();
    }

    public static com.sandbox.filesystem.WatchDirResponse.KeepAlive getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeepAlive>
        PARSER = new com.google.protobuf.AbstractParser<KeepAlive>() {
      @java.lang.Override
      public KeepAlive parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KeepAlive> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeepAlive> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse.KeepAlive getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int eventCase_ = 0;
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    START(1),
    FILESYSTEM(2),
    KEEPALIVE(3),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 1: return START;
        case 2: return FILESYSTEM;
        case 3: return KEEPALIVE;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int START_FIELD_NUMBER = 1;
  /**
   * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
   * @return Whether the start field is set.
   */
  @java.lang.Override
  public boolean hasStart() {
    return eventCase_ == 1;
  }
  /**
   * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
   * @return The start.
   */
  @java.lang.Override
  public com.sandbox.filesystem.WatchDirResponse.StartEvent getStart() {
    if (eventCase_ == 1) {
       return (com.sandbox.filesystem.WatchDirResponse.StartEvent) event_;
    }
    return com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance();
  }
  /**
   * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
   */
  @java.lang.Override
  public com.sandbox.filesystem.WatchDirResponse.StartEventOrBuilder getStartOrBuilder() {
    if (eventCase_ == 1) {
       return (com.sandbox.filesystem.WatchDirResponse.StartEvent) event_;
    }
    return com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance();
  }

  public static final int FILESYSTEM_FIELD_NUMBER = 2;
  /**
   * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
   * @return Whether the filesystem field is set.
   */
  @java.lang.Override
  public boolean hasFilesystem() {
    return eventCase_ == 2;
  }
  /**
   * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
   * @return The filesystem.
   */
  @java.lang.Override
  public com.sandbox.filesystem.FilesystemEvent getFilesystem() {
    if (eventCase_ == 2) {
       return (com.sandbox.filesystem.FilesystemEvent) event_;
    }
    return com.sandbox.filesystem.FilesystemEvent.getDefaultInstance();
  }
  /**
   * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
   */
  @java.lang.Override
  public com.sandbox.filesystem.FilesystemEventOrBuilder getFilesystemOrBuilder() {
    if (eventCase_ == 2) {
       return (com.sandbox.filesystem.FilesystemEvent) event_;
    }
    return com.sandbox.filesystem.FilesystemEvent.getDefaultInstance();
  }

  public static final int KEEPALIVE_FIELD_NUMBER = 3;
  /**
   * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   * @return Whether the keepalive field is set.
   */
  @java.lang.Override
  public boolean hasKeepalive() {
    return eventCase_ == 3;
  }
  /**
   * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   * @return The keepalive.
   */
  @java.lang.Override
  public com.sandbox.filesystem.WatchDirResponse.KeepAlive getKeepalive() {
    if (eventCase_ == 3) {
       return (com.sandbox.filesystem.WatchDirResponse.KeepAlive) event_;
    }
    return com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance();
  }
  /**
   * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   */
  @java.lang.Override
  public com.sandbox.filesystem.WatchDirResponse.KeepAliveOrBuilder getKeepaliveOrBuilder() {
    if (eventCase_ == 3) {
       return (com.sandbox.filesystem.WatchDirResponse.KeepAlive) event_;
    }
    return com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 1) {
      output.writeMessage(1, (com.sandbox.filesystem.WatchDirResponse.StartEvent) event_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (com.sandbox.filesystem.FilesystemEvent) event_);
    }
    if (eventCase_ == 3) {
      output.writeMessage(3, (com.sandbox.filesystem.WatchDirResponse.KeepAlive) event_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.sandbox.filesystem.WatchDirResponse.StartEvent) event_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.sandbox.filesystem.FilesystemEvent) event_);
    }
    if (eventCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.sandbox.filesystem.WatchDirResponse.KeepAlive) event_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sandbox.filesystem.WatchDirResponse)) {
      return super.equals(obj);
    }
    com.sandbox.filesystem.WatchDirResponse other = (com.sandbox.filesystem.WatchDirResponse) obj;

    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 1:
        if (!getStart()
            .equals(other.getStart())) return false;
        break;
      case 2:
        if (!getFilesystem()
            .equals(other.getFilesystem())) return false;
        break;
      case 3:
        if (!getKeepalive()
            .equals(other.getKeepalive())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (eventCase_) {
      case 1:
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
        break;
      case 2:
        hash = (37 * hash) + FILESYSTEM_FIELD_NUMBER;
        hash = (53 * hash) + getFilesystem().hashCode();
        break;
      case 3:
        hash = (37 * hash) + KEEPALIVE_FIELD_NUMBER;
        hash = (53 * hash) + getKeepalive().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sandbox.filesystem.WatchDirResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.filesystem.WatchDirResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sandbox.filesystem.WatchDirResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code filesystem.WatchDirResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:filesystem.WatchDirResponse)
      com.sandbox.filesystem.WatchDirResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.filesystem.WatchDirResponse.class, com.sandbox.filesystem.WatchDirResponse.Builder.class);
    }

    // Construct using com.sandbox.filesystem.WatchDirResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (startBuilder_ != null) {
        startBuilder_.clear();
      }
      if (filesystemBuilder_ != null) {
        filesystemBuilder_.clear();
      }
      if (keepaliveBuilder_ != null) {
        keepaliveBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sandbox.filesystem.FilesystemProto.internal_static_filesystem_WatchDirResponse_descriptor;
    }

    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse getDefaultInstanceForType() {
      return com.sandbox.filesystem.WatchDirResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse build() {
      com.sandbox.filesystem.WatchDirResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse buildPartial() {
      com.sandbox.filesystem.WatchDirResponse result = new com.sandbox.filesystem.WatchDirResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sandbox.filesystem.WatchDirResponse result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.sandbox.filesystem.WatchDirResponse result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 1 &&
          startBuilder_ != null) {
        result.event_ = startBuilder_.build();
      }
      if (eventCase_ == 2 &&
          filesystemBuilder_ != null) {
        result.event_ = filesystemBuilder_.build();
      }
      if (eventCase_ == 3 &&
          keepaliveBuilder_ != null) {
        result.event_ = keepaliveBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sandbox.filesystem.WatchDirResponse) {
        return mergeFrom((com.sandbox.filesystem.WatchDirResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sandbox.filesystem.WatchDirResponse other) {
      if (other == com.sandbox.filesystem.WatchDirResponse.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case START: {
          mergeStart(other.getStart());
          break;
        }
        case FILESYSTEM: {
          mergeFilesystem(other.getFilesystem());
          break;
        }
        case KEEPALIVE: {
          mergeKeepalive(other.getKeepalive());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStartFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getFilesystemFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getKeepaliveFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.filesystem.WatchDirResponse.StartEvent, com.sandbox.filesystem.WatchDirResponse.StartEvent.Builder, com.sandbox.filesystem.WatchDirResponse.StartEventOrBuilder> startBuilder_;
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return eventCase_ == 1;
    }
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     * @return The start.
     */
    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse.StartEvent getStart() {
      if (startBuilder_ == null) {
        if (eventCase_ == 1) {
          return (com.sandbox.filesystem.WatchDirResponse.StartEvent) event_;
        }
        return com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 1) {
          return startBuilder_.getMessage();
        }
        return com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     */
    public Builder setStart(com.sandbox.filesystem.WatchDirResponse.StartEvent value) {
      if (startBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        startBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     */
    public Builder setStart(
        com.sandbox.filesystem.WatchDirResponse.StartEvent.Builder builderForValue) {
      if (startBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        startBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     */
    public Builder mergeStart(com.sandbox.filesystem.WatchDirResponse.StartEvent value) {
      if (startBuilder_ == null) {
        if (eventCase_ == 1 &&
            event_ != com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance()) {
          event_ = com.sandbox.filesystem.WatchDirResponse.StartEvent.newBuilder((com.sandbox.filesystem.WatchDirResponse.StartEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 1) {
          startBuilder_.mergeFrom(value);
        } else {
          startBuilder_.setMessage(value);
        }
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     */
    public Builder clearStart() {
      if (startBuilder_ == null) {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
        }
        startBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     */
    public com.sandbox.filesystem.WatchDirResponse.StartEvent.Builder getStartBuilder() {
      return getStartFieldBuilder().getBuilder();
    }
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     */
    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse.StartEventOrBuilder getStartOrBuilder() {
      if ((eventCase_ == 1) && (startBuilder_ != null)) {
        return startBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 1) {
          return (com.sandbox.filesystem.WatchDirResponse.StartEvent) event_;
        }
        return com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.filesystem.WatchDirResponse.StartEvent start = 1 [json_name = "start"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.filesystem.WatchDirResponse.StartEvent, com.sandbox.filesystem.WatchDirResponse.StartEvent.Builder, com.sandbox.filesystem.WatchDirResponse.StartEventOrBuilder> 
        getStartFieldBuilder() {
      if (startBuilder_ == null) {
        if (!(eventCase_ == 1)) {
          event_ = com.sandbox.filesystem.WatchDirResponse.StartEvent.getDefaultInstance();
        }
        startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.filesystem.WatchDirResponse.StartEvent, com.sandbox.filesystem.WatchDirResponse.StartEvent.Builder, com.sandbox.filesystem.WatchDirResponse.StartEventOrBuilder>(
                (com.sandbox.filesystem.WatchDirResponse.StartEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 1;
      onChanged();
      return startBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.filesystem.FilesystemEvent, com.sandbox.filesystem.FilesystemEvent.Builder, com.sandbox.filesystem.FilesystemEventOrBuilder> filesystemBuilder_;
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     * @return Whether the filesystem field is set.
     */
    @java.lang.Override
    public boolean hasFilesystem() {
      return eventCase_ == 2;
    }
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     * @return The filesystem.
     */
    @java.lang.Override
    public com.sandbox.filesystem.FilesystemEvent getFilesystem() {
      if (filesystemBuilder_ == null) {
        if (eventCase_ == 2) {
          return (com.sandbox.filesystem.FilesystemEvent) event_;
        }
        return com.sandbox.filesystem.FilesystemEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return filesystemBuilder_.getMessage();
        }
        return com.sandbox.filesystem.FilesystemEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     */
    public Builder setFilesystem(com.sandbox.filesystem.FilesystemEvent value) {
      if (filesystemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        filesystemBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     */
    public Builder setFilesystem(
        com.sandbox.filesystem.FilesystemEvent.Builder builderForValue) {
      if (filesystemBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        filesystemBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     */
    public Builder mergeFilesystem(com.sandbox.filesystem.FilesystemEvent value) {
      if (filesystemBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != com.sandbox.filesystem.FilesystemEvent.getDefaultInstance()) {
          event_ = com.sandbox.filesystem.FilesystemEvent.newBuilder((com.sandbox.filesystem.FilesystemEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          filesystemBuilder_.mergeFrom(value);
        } else {
          filesystemBuilder_.setMessage(value);
        }
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     */
    public Builder clearFilesystem() {
      if (filesystemBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        filesystemBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     */
    public com.sandbox.filesystem.FilesystemEvent.Builder getFilesystemBuilder() {
      return getFilesystemFieldBuilder().getBuilder();
    }
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     */
    @java.lang.Override
    public com.sandbox.filesystem.FilesystemEventOrBuilder getFilesystemOrBuilder() {
      if ((eventCase_ == 2) && (filesystemBuilder_ != null)) {
        return filesystemBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (com.sandbox.filesystem.FilesystemEvent) event_;
        }
        return com.sandbox.filesystem.FilesystemEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.filesystem.FilesystemEvent filesystem = 2 [json_name = "filesystem"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.filesystem.FilesystemEvent, com.sandbox.filesystem.FilesystemEvent.Builder, com.sandbox.filesystem.FilesystemEventOrBuilder> 
        getFilesystemFieldBuilder() {
      if (filesystemBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = com.sandbox.filesystem.FilesystemEvent.getDefaultInstance();
        }
        filesystemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.filesystem.FilesystemEvent, com.sandbox.filesystem.FilesystemEvent.Builder, com.sandbox.filesystem.FilesystemEventOrBuilder>(
                (com.sandbox.filesystem.FilesystemEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();
      return filesystemBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.filesystem.WatchDirResponse.KeepAlive, com.sandbox.filesystem.WatchDirResponse.KeepAlive.Builder, com.sandbox.filesystem.WatchDirResponse.KeepAliveOrBuilder> keepaliveBuilder_;
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     * @return Whether the keepalive field is set.
     */
    @java.lang.Override
    public boolean hasKeepalive() {
      return eventCase_ == 3;
    }
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     * @return The keepalive.
     */
    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse.KeepAlive getKeepalive() {
      if (keepaliveBuilder_ == null) {
        if (eventCase_ == 3) {
          return (com.sandbox.filesystem.WatchDirResponse.KeepAlive) event_;
        }
        return com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance();
      } else {
        if (eventCase_ == 3) {
          return keepaliveBuilder_.getMessage();
        }
        return com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance();
      }
    }
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public Builder setKeepalive(com.sandbox.filesystem.WatchDirResponse.KeepAlive value) {
      if (keepaliveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        keepaliveBuilder_.setMessage(value);
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public Builder setKeepalive(
        com.sandbox.filesystem.WatchDirResponse.KeepAlive.Builder builderForValue) {
      if (keepaliveBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        keepaliveBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public Builder mergeKeepalive(com.sandbox.filesystem.WatchDirResponse.KeepAlive value) {
      if (keepaliveBuilder_ == null) {
        if (eventCase_ == 3 &&
            event_ != com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance()) {
          event_ = com.sandbox.filesystem.WatchDirResponse.KeepAlive.newBuilder((com.sandbox.filesystem.WatchDirResponse.KeepAlive) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 3) {
          keepaliveBuilder_.mergeFrom(value);
        } else {
          keepaliveBuilder_.setMessage(value);
        }
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public Builder clearKeepalive() {
      if (keepaliveBuilder_ == null) {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
        }
        keepaliveBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public com.sandbox.filesystem.WatchDirResponse.KeepAlive.Builder getKeepaliveBuilder() {
      return getKeepaliveFieldBuilder().getBuilder();
    }
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    @java.lang.Override
    public com.sandbox.filesystem.WatchDirResponse.KeepAliveOrBuilder getKeepaliveOrBuilder() {
      if ((eventCase_ == 3) && (keepaliveBuilder_ != null)) {
        return keepaliveBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 3) {
          return (com.sandbox.filesystem.WatchDirResponse.KeepAlive) event_;
        }
        return com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance();
      }
    }
    /**
     * <code>.filesystem.WatchDirResponse.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.filesystem.WatchDirResponse.KeepAlive, com.sandbox.filesystem.WatchDirResponse.KeepAlive.Builder, com.sandbox.filesystem.WatchDirResponse.KeepAliveOrBuilder> 
        getKeepaliveFieldBuilder() {
      if (keepaliveBuilder_ == null) {
        if (!(eventCase_ == 3)) {
          event_ = com.sandbox.filesystem.WatchDirResponse.KeepAlive.getDefaultInstance();
        }
        keepaliveBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.filesystem.WatchDirResponse.KeepAlive, com.sandbox.filesystem.WatchDirResponse.KeepAlive.Builder, com.sandbox.filesystem.WatchDirResponse.KeepAliveOrBuilder>(
                (com.sandbox.filesystem.WatchDirResponse.KeepAlive) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 3;
      onChanged();
      return keepaliveBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:filesystem.WatchDirResponse)
  }

  // @@protoc_insertion_point(class_scope:filesystem.WatchDirResponse)
  private static final com.sandbox.filesystem.WatchDirResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sandbox.filesystem.WatchDirResponse();
  }

  public static com.sandbox.filesystem.WatchDirResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WatchDirResponse>
      PARSER = new com.google.protobuf.AbstractParser<WatchDirResponse>() {
    @java.lang.Override
    public WatchDirResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WatchDirResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WatchDirResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sandbox.filesystem.WatchDirResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

