// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

/**
 * Protobuf type {@code process.ConnectRequest}
 */
public final class ConnectRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:process.ConnectRequest)
    ConnectRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConnectRequest.newBuilder() to construct.
  private ConnectRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConnectRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConnectRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sandbox.process.ProcessProto.internal_static_process_ConnectRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sandbox.process.ProcessProto.internal_static_process_ConnectRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sandbox.process.ConnectRequest.class, com.sandbox.process.ConnectRequest.Builder.class);
  }

  public static final int PROCESS_FIELD_NUMBER = 1;
  private com.sandbox.process.ProcessSelector process_;
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  @java.lang.Override
  public boolean hasProcess() {
    return process_ != null;
  }
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  @java.lang.Override
  public com.sandbox.process.ProcessSelector getProcess() {
    return process_ == null ? com.sandbox.process.ProcessSelector.getDefaultInstance() : process_;
  }
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   */
  @java.lang.Override
  public com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder() {
    return process_ == null ? com.sandbox.process.ProcessSelector.getDefaultInstance() : process_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (process_ != null) {
      output.writeMessage(1, getProcess());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (process_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProcess());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sandbox.process.ConnectRequest)) {
      return super.equals(obj);
    }
    com.sandbox.process.ConnectRequest other = (com.sandbox.process.ConnectRequest) obj;

    if (hasProcess() != other.hasProcess()) return false;
    if (hasProcess()) {
      if (!getProcess()
          .equals(other.getProcess())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProcess()) {
      hash = (37 * hash) + PROCESS_FIELD_NUMBER;
      hash = (53 * hash) + getProcess().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sandbox.process.ConnectRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.process.ConnectRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sandbox.process.ConnectRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.process.ConnectRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sandbox.process.ConnectRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code process.ConnectRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:process.ConnectRequest)
      com.sandbox.process.ConnectRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.process.ProcessProto.internal_static_process_ConnectRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.process.ProcessProto.internal_static_process_ConnectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.process.ConnectRequest.class, com.sandbox.process.ConnectRequest.Builder.class);
    }

    // Construct using com.sandbox.process.ConnectRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      process_ = null;
      if (processBuilder_ != null) {
        processBuilder_.dispose();
        processBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sandbox.process.ProcessProto.internal_static_process_ConnectRequest_descriptor;
    }

    @java.lang.Override
    public com.sandbox.process.ConnectRequest getDefaultInstanceForType() {
      return com.sandbox.process.ConnectRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sandbox.process.ConnectRequest build() {
      com.sandbox.process.ConnectRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sandbox.process.ConnectRequest buildPartial() {
      com.sandbox.process.ConnectRequest result = new com.sandbox.process.ConnectRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sandbox.process.ConnectRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.process_ = processBuilder_ == null
            ? process_
            : processBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sandbox.process.ConnectRequest) {
        return mergeFrom((com.sandbox.process.ConnectRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sandbox.process.ConnectRequest other) {
      if (other == com.sandbox.process.ConnectRequest.getDefaultInstance()) return this;
      if (other.hasProcess()) {
        mergeProcess(other.getProcess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getProcessFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.sandbox.process.ProcessSelector process_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.ProcessSelector, com.sandbox.process.ProcessSelector.Builder, com.sandbox.process.ProcessSelectorOrBuilder> processBuilder_;
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     * @return Whether the process field is set.
     */
    public boolean hasProcess() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     * @return The process.
     */
    public com.sandbox.process.ProcessSelector getProcess() {
      if (processBuilder_ == null) {
        return process_ == null ? com.sandbox.process.ProcessSelector.getDefaultInstance() : process_;
      } else {
        return processBuilder_.getMessage();
      }
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public Builder setProcess(com.sandbox.process.ProcessSelector value) {
      if (processBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        process_ = value;
      } else {
        processBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public Builder setProcess(
        com.sandbox.process.ProcessSelector.Builder builderForValue) {
      if (processBuilder_ == null) {
        process_ = builderForValue.build();
      } else {
        processBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public Builder mergeProcess(com.sandbox.process.ProcessSelector value) {
      if (processBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          process_ != null &&
          process_ != com.sandbox.process.ProcessSelector.getDefaultInstance()) {
          getProcessBuilder().mergeFrom(value);
        } else {
          process_ = value;
        }
      } else {
        processBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public Builder clearProcess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      process_ = null;
      if (processBuilder_ != null) {
        processBuilder_.dispose();
        processBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public com.sandbox.process.ProcessSelector.Builder getProcessBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getProcessFieldBuilder().getBuilder();
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder() {
      if (processBuilder_ != null) {
        return processBuilder_.getMessageOrBuilder();
      } else {
        return process_ == null ?
            com.sandbox.process.ProcessSelector.getDefaultInstance() : process_;
      }
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.ProcessSelector, com.sandbox.process.ProcessSelector.Builder, com.sandbox.process.ProcessSelectorOrBuilder> 
        getProcessFieldBuilder() {
      if (processBuilder_ == null) {
        processBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.process.ProcessSelector, com.sandbox.process.ProcessSelector.Builder, com.sandbox.process.ProcessSelectorOrBuilder>(
                getProcess(),
                getParentForChildren(),
                isClean());
        process_ = null;
      }
      return processBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:process.ConnectRequest)
  }

  // @@protoc_insertion_point(class_scope:process.ConnectRequest)
  private static final com.sandbox.process.ConnectRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sandbox.process.ConnectRequest();
  }

  public static com.sandbox.process.ConnectRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConnectRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConnectRequest>() {
    @java.lang.Override
    public ConnectRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConnectRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConnectRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sandbox.process.ConnectRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

