// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface ConnectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.ConnectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  boolean hasProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  com.sandbox.process.ProcessSelector getProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   */
  com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder();
}
