// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .process.ProcessInfo processes = 1 [json_name = "processes"];</code>
   */
  java.util.List<com.sandbox.process.ProcessInfo> 
      getProcessesList();
  /**
   * <code>repeated .process.ProcessInfo processes = 1 [json_name = "processes"];</code>
   */
  com.sandbox.process.ProcessInfo getProcesses(int index);
  /**
   * <code>repeated .process.ProcessInfo processes = 1 [json_name = "processes"];</code>
   */
  int getProcessesCount();
  /**
   * <code>repeated .process.ProcessInfo processes = 1 [json_name = "processes"];</code>
   */
  java.util.List<? extends com.sandbox.process.ProcessInfoOrBuilder> 
      getProcessesOrBuilderList();
  /**
   * <code>repeated .process.ProcessInfo processes = 1 [json_name = "processes"];</code>
   */
  com.sandbox.process.ProcessInfoOrBuilder getProcessesOrBuilder(
      int index);
}
