// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface ProcessInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.ProcessInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessConfig config = 1 [json_name = "config"];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.process.ProcessConfig config = 1 [json_name = "config"];</code>
   * @return The config.
   */
  com.sandbox.process.ProcessConfig getConfig();
  /**
   * <code>.process.ProcessConfig config = 1 [json_name = "config"];</code>
   */
  com.sandbox.process.ProcessConfigOrBuilder getConfigOrBuilder();

  /**
   * <code>uint32 pid = 2 [json_name = "pid"];</code>
   * @return The pid.
   */
  int getPid();

  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return Whether the tag field is set.
   */
  boolean hasTag();
  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
