// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface ProcessEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.ProcessEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessEvent.StartEvent start = 1 [json_name = "start"];</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <code>.process.ProcessEvent.StartEvent start = 1 [json_name = "start"];</code>
   * @return The start.
   */
  com.sandbox.process.ProcessEvent.StartEvent getStart();
  /**
   * <code>.process.ProcessEvent.StartEvent start = 1 [json_name = "start"];</code>
   */
  com.sandbox.process.ProcessEvent.StartEventOrBuilder getStartOrBuilder();

  /**
   * <code>.process.ProcessEvent.DataEvent data = 2 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.process.ProcessEvent.DataEvent data = 2 [json_name = "data"];</code>
   * @return The data.
   */
  com.sandbox.process.ProcessEvent.DataEvent getData();
  /**
   * <code>.process.ProcessEvent.DataEvent data = 2 [json_name = "data"];</code>
   */
  com.sandbox.process.ProcessEvent.DataEventOrBuilder getDataOrBuilder();

  /**
   * <code>.process.ProcessEvent.EndEvent end = 3 [json_name = "end"];</code>
   * @return Whether the end field is set.
   */
  boolean hasEnd();
  /**
   * <code>.process.ProcessEvent.EndEvent end = 3 [json_name = "end"];</code>
   * @return The end.
   */
  com.sandbox.process.ProcessEvent.EndEvent getEnd();
  /**
   * <code>.process.ProcessEvent.EndEvent end = 3 [json_name = "end"];</code>
   */
  com.sandbox.process.ProcessEvent.EndEventOrBuilder getEndOrBuilder();

  /**
   * <code>.process.ProcessEvent.KeepAlive keepalive = 4 [json_name = "keepalive"];</code>
   * @return Whether the keepalive field is set.
   */
  boolean hasKeepalive();
  /**
   * <code>.process.ProcessEvent.KeepAlive keepalive = 4 [json_name = "keepalive"];</code>
   * @return The keepalive.
   */
  com.sandbox.process.ProcessEvent.KeepAlive getKeepalive();
  /**
   * <code>.process.ProcessEvent.KeepAlive keepalive = 4 [json_name = "keepalive"];</code>
   */
  com.sandbox.process.ProcessEvent.KeepAliveOrBuilder getKeepaliveOrBuilder();

  public com.sandbox.process.ProcessEvent.EventCase getEventCase();
}
