// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface ProcessConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.ProcessConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cmd = 1 [json_name = "cmd"];</code>
   * @return The cmd.
   */
  java.lang.String getCmd();
  /**
   * <code>string cmd = 1 [json_name = "cmd"];</code>
   * @return The bytes for cmd.
   */
  com.google.protobuf.ByteString
      getCmdBytes();

  /**
   * <code>repeated string args = 2 [json_name = "args"];</code>
   * @return A list containing the args.
   */
  java.util.List<java.lang.String>
      getArgsList();
  /**
   * <code>repeated string args = 2 [json_name = "args"];</code>
   * @return The count of args.
   */
  int getArgsCount();
  /**
   * <code>repeated string args = 2 [json_name = "args"];</code>
   * @param index The index of the element to return.
   * @return The args at the given index.
   */
  java.lang.String getArgs(int index);
  /**
   * <code>repeated string args = 2 [json_name = "args"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the args at the given index.
   */
  com.google.protobuf.ByteString
      getArgsBytes(int index);

  /**
   * <code>map&lt;string, string&gt; envs = 3 [json_name = "envs"];</code>
   */
  int getEnvsCount();
  /**
   * <code>map&lt;string, string&gt; envs = 3 [json_name = "envs"];</code>
   */
  boolean containsEnvs(
      java.lang.String key);
  /**
   * Use {@link #getEnvsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getEnvs();
  /**
   * <code>map&lt;string, string&gt; envs = 3 [json_name = "envs"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getEnvsMap();
  /**
   * <code>map&lt;string, string&gt; envs = 3 [json_name = "envs"];</code>
   */
  /* nullable */
java.lang.String getEnvsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; envs = 3 [json_name = "envs"];</code>
   */
  java.lang.String getEnvsOrThrow(
      java.lang.String key);

  /**
   * <code>optional string cwd = 4 [json_name = "cwd"];</code>
   * @return Whether the cwd field is set.
   */
  boolean hasCwd();
  /**
   * <code>optional string cwd = 4 [json_name = "cwd"];</code>
   * @return The cwd.
   */
  java.lang.String getCwd();
  /**
   * <code>optional string cwd = 4 [json_name = "cwd"];</code>
   * @return The bytes for cwd.
   */
  com.google.protobuf.ByteString
      getCwdBytes();
}
