// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface ProcessInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.ProcessInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes stdin = 1 [json_name = "stdin"];</code>
   * @return Whether the stdin field is set.
   */
  boolean hasStdin();
  /**
   * <code>bytes stdin = 1 [json_name = "stdin"];</code>
   * @return The stdin.
   */
  com.google.protobuf.ByteString getStdin();

  /**
   * <code>bytes pty = 2 [json_name = "pty"];</code>
   * @return Whether the pty field is set.
   */
  boolean hasPty();
  /**
   * <code>bytes pty = 2 [json_name = "pty"];</code>
   * @return The pty.
   */
  com.google.protobuf.ByteString getPty();

  public com.sandbox.process.ProcessInput.InputCase getInputCase();
}
