// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

/**
 * Protobuf type {@code process.ProcessInput}
 */
public final class ProcessInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:process.ProcessInput)
    ProcessInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProcessInput.newBuilder() to construct.
  private ProcessInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProcessInput() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProcessInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sandbox.process.ProcessProto.internal_static_process_ProcessInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sandbox.process.ProcessProto.internal_static_process_ProcessInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sandbox.process.ProcessInput.class, com.sandbox.process.ProcessInput.Builder.class);
  }

  private int inputCase_ = 0;
  private java.lang.Object input_;
  public enum InputCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STDIN(1),
    PTY(2),
    INPUT_NOT_SET(0);
    private final int value;
    private InputCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InputCase valueOf(int value) {
      return forNumber(value);
    }

    public static InputCase forNumber(int value) {
      switch (value) {
        case 1: return STDIN;
        case 2: return PTY;
        case 0: return INPUT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public InputCase
  getInputCase() {
    return InputCase.forNumber(
        inputCase_);
  }

  public static final int STDIN_FIELD_NUMBER = 1;
  /**
   * <code>bytes stdin = 1 [json_name = "stdin"];</code>
   * @return Whether the stdin field is set.
   */
  @java.lang.Override
  public boolean hasStdin() {
    return inputCase_ == 1;
  }
  /**
   * <code>bytes stdin = 1 [json_name = "stdin"];</code>
   * @return The stdin.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStdin() {
    if (inputCase_ == 1) {
      return (com.google.protobuf.ByteString) input_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int PTY_FIELD_NUMBER = 2;
  /**
   * <code>bytes pty = 2 [json_name = "pty"];</code>
   * @return Whether the pty field is set.
   */
  @java.lang.Override
  public boolean hasPty() {
    return inputCase_ == 2;
  }
  /**
   * <code>bytes pty = 2 [json_name = "pty"];</code>
   * @return The pty.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPty() {
    if (inputCase_ == 2) {
      return (com.google.protobuf.ByteString) input_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (inputCase_ == 1) {
      output.writeBytes(
          1, (com.google.protobuf.ByteString) input_);
    }
    if (inputCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) input_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (inputCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            1, (com.google.protobuf.ByteString) input_);
    }
    if (inputCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) input_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sandbox.process.ProcessInput)) {
      return super.equals(obj);
    }
    com.sandbox.process.ProcessInput other = (com.sandbox.process.ProcessInput) obj;

    if (!getInputCase().equals(other.getInputCase())) return false;
    switch (inputCase_) {
      case 1:
        if (!getStdin()
            .equals(other.getStdin())) return false;
        break;
      case 2:
        if (!getPty()
            .equals(other.getPty())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (inputCase_) {
      case 1:
        hash = (37 * hash) + STDIN_FIELD_NUMBER;
        hash = (53 * hash) + getStdin().hashCode();
        break;
      case 2:
        hash = (37 * hash) + PTY_FIELD_NUMBER;
        hash = (53 * hash) + getPty().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sandbox.process.ProcessInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.ProcessInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.ProcessInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.ProcessInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.ProcessInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.ProcessInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.ProcessInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.process.ProcessInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.process.ProcessInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sandbox.process.ProcessInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.process.ProcessInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.process.ProcessInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sandbox.process.ProcessInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code process.ProcessInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:process.ProcessInput)
      com.sandbox.process.ProcessInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.process.ProcessProto.internal_static_process_ProcessInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.process.ProcessProto.internal_static_process_ProcessInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.process.ProcessInput.class, com.sandbox.process.ProcessInput.Builder.class);
    }

    // Construct using com.sandbox.process.ProcessInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      inputCase_ = 0;
      input_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sandbox.process.ProcessProto.internal_static_process_ProcessInput_descriptor;
    }

    @java.lang.Override
    public com.sandbox.process.ProcessInput getDefaultInstanceForType() {
      return com.sandbox.process.ProcessInput.getDefaultInstance();
    }

    @java.lang.Override
    public com.sandbox.process.ProcessInput build() {
      com.sandbox.process.ProcessInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sandbox.process.ProcessInput buildPartial() {
      com.sandbox.process.ProcessInput result = new com.sandbox.process.ProcessInput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sandbox.process.ProcessInput result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.sandbox.process.ProcessInput result) {
      result.inputCase_ = inputCase_;
      result.input_ = this.input_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sandbox.process.ProcessInput) {
        return mergeFrom((com.sandbox.process.ProcessInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sandbox.process.ProcessInput other) {
      if (other == com.sandbox.process.ProcessInput.getDefaultInstance()) return this;
      switch (other.getInputCase()) {
        case STDIN: {
          setStdin(other.getStdin());
          break;
        }
        case PTY: {
          setPty(other.getPty());
          break;
        }
        case INPUT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input_ = input.readBytes();
              inputCase_ = 1;
              break;
            } // case 10
            case 18: {
              input_ = input.readBytes();
              inputCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int inputCase_ = 0;
    private java.lang.Object input_;
    public InputCase
        getInputCase() {
      return InputCase.forNumber(
          inputCase_);
    }

    public Builder clearInput() {
      inputCase_ = 0;
      input_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>bytes stdin = 1 [json_name = "stdin"];</code>
     * @return Whether the stdin field is set.
     */
    public boolean hasStdin() {
      return inputCase_ == 1;
    }
    /**
     * <code>bytes stdin = 1 [json_name = "stdin"];</code>
     * @return The stdin.
     */
    public com.google.protobuf.ByteString getStdin() {
      if (inputCase_ == 1) {
        return (com.google.protobuf.ByteString) input_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes stdin = 1 [json_name = "stdin"];</code>
     * @param value The stdin to set.
     * @return This builder for chaining.
     */
    public Builder setStdin(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      inputCase_ = 1;
      input_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes stdin = 1 [json_name = "stdin"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStdin() {
      if (inputCase_ == 1) {
        inputCase_ = 0;
        input_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bytes pty = 2 [json_name = "pty"];</code>
     * @return Whether the pty field is set.
     */
    public boolean hasPty() {
      return inputCase_ == 2;
    }
    /**
     * <code>bytes pty = 2 [json_name = "pty"];</code>
     * @return The pty.
     */
    public com.google.protobuf.ByteString getPty() {
      if (inputCase_ == 2) {
        return (com.google.protobuf.ByteString) input_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes pty = 2 [json_name = "pty"];</code>
     * @param value The pty to set.
     * @return This builder for chaining.
     */
    public Builder setPty(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      inputCase_ = 2;
      input_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes pty = 2 [json_name = "pty"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPty() {
      if (inputCase_ == 2) {
        inputCase_ = 0;
        input_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:process.ProcessInput)
  }

  // @@protoc_insertion_point(class_scope:process.ProcessInput)
  private static final com.sandbox.process.ProcessInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sandbox.process.ProcessInput();
  }

  public static com.sandbox.process.ProcessInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProcessInput>
      PARSER = new com.google.protobuf.AbstractParser<ProcessInput>() {
    @java.lang.Override
    public ProcessInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProcessInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProcessInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sandbox.process.ProcessInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

