// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface SendSignalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.SendSignalResponse)
    com.google.protobuf.MessageOrBuilder {
}
