// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface SendInputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.SendInputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  boolean hasProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  com.sandbox.process.ProcessSelector getProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   */
  com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder();

  /**
   * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
   * @return The input.
   */
  com.sandbox.process.ProcessInput getInput();
  /**
   * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
   */
  com.sandbox.process.ProcessInputOrBuilder getInputOrBuilder();
}
