// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface SendSignalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.SendSignalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  boolean hasProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  com.sandbox.process.ProcessSelector getProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   */
  com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder();

  /**
   * <code>.process.Signal signal = 2 [json_name = "signal"];</code>
   * @return The enum numeric value on the wire for signal.
   */
  int getSignalValue();
  /**
   * <code>.process.Signal signal = 2 [json_name = "signal"];</code>
   * @return The signal.
   */
  com.sandbox.process.Signal getSignal();
}
