// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface StartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.StartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  boolean hasProcess();
  /**
   * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  com.sandbox.process.ProcessConfig getProcess();
  /**
   * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
   */
  com.sandbox.process.ProcessConfigOrBuilder getProcessOrBuilder();

  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   * @return Whether the pty field is set.
   */
  boolean hasPty();
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   * @return The pty.
   */
  com.sandbox.process.PTY getPty();
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   */
  com.sandbox.process.PTYOrBuilder getPtyOrBuilder();

  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return Whether the tag field is set.
   */
  boolean hasTag();
  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>optional bool stdin = 4 [json_name = "stdin"];</code>
   * @return Whether the stdin field is set.
   */
  boolean hasStdin();
  /**
   * <code>optional bool stdin = 4 [json_name = "stdin"];</code>
   * @return The stdin.
   */
  boolean getStdin();
}
