// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

/**
 * Protobuf type {@code process.StartRequest}
 */
public final class StartRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:process.StartRequest)
    StartRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StartRequest.newBuilder() to construct.
  private StartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StartRequest() {
    tag_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StartRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sandbox.process.ProcessProto.internal_static_process_StartRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sandbox.process.ProcessProto.internal_static_process_StartRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sandbox.process.StartRequest.class, com.sandbox.process.StartRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PROCESS_FIELD_NUMBER = 1;
  private com.sandbox.process.ProcessConfig process_;
  /**
   * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  @java.lang.Override
  public boolean hasProcess() {
    return process_ != null;
  }
  /**
   * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  @java.lang.Override
  public com.sandbox.process.ProcessConfig getProcess() {
    return process_ == null ? com.sandbox.process.ProcessConfig.getDefaultInstance() : process_;
  }
  /**
   * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
   */
  @java.lang.Override
  public com.sandbox.process.ProcessConfigOrBuilder getProcessOrBuilder() {
    return process_ == null ? com.sandbox.process.ProcessConfig.getDefaultInstance() : process_;
  }

  public static final int PTY_FIELD_NUMBER = 2;
  private com.sandbox.process.PTY pty_;
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   * @return Whether the pty field is set.
   */
  @java.lang.Override
  public boolean hasPty() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   * @return The pty.
   */
  @java.lang.Override
  public com.sandbox.process.PTY getPty() {
    return pty_ == null ? com.sandbox.process.PTY.getDefaultInstance() : pty_;
  }
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   */
  @java.lang.Override
  public com.sandbox.process.PTYOrBuilder getPtyOrBuilder() {
    return pty_ == null ? com.sandbox.process.PTY.getDefaultInstance() : pty_;
  }

  public static final int TAG_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tag_ = "";
  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return Whether the tag field is set.
   */
  @java.lang.Override
  public boolean hasTag() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return The tag.
   */
  @java.lang.Override
  public java.lang.String getTag() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tag_ = s;
      return s;
    }
  }
  /**
   * <code>optional string tag = 3 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTagBytes() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STDIN_FIELD_NUMBER = 4;
  private boolean stdin_ = false;
  /**
   * <code>optional bool stdin = 4 [json_name = "stdin"];</code>
   * @return Whether the stdin field is set.
   */
  @java.lang.Override
  public boolean hasStdin() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional bool stdin = 4 [json_name = "stdin"];</code>
   * @return The stdin.
   */
  @java.lang.Override
  public boolean getStdin() {
    return stdin_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (process_ != null) {
      output.writeMessage(1, getProcess());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPty());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tag_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(4, stdin_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (process_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProcess());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPty());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tag_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, stdin_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sandbox.process.StartRequest)) {
      return super.equals(obj);
    }
    com.sandbox.process.StartRequest other = (com.sandbox.process.StartRequest) obj;

    if (hasProcess() != other.hasProcess()) return false;
    if (hasProcess()) {
      if (!getProcess()
          .equals(other.getProcess())) return false;
    }
    if (hasPty() != other.hasPty()) return false;
    if (hasPty()) {
      if (!getPty()
          .equals(other.getPty())) return false;
    }
    if (hasTag() != other.hasTag()) return false;
    if (hasTag()) {
      if (!getTag()
          .equals(other.getTag())) return false;
    }
    if (hasStdin() != other.hasStdin()) return false;
    if (hasStdin()) {
      if (getStdin()
          != other.getStdin()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProcess()) {
      hash = (37 * hash) + PROCESS_FIELD_NUMBER;
      hash = (53 * hash) + getProcess().hashCode();
    }
    if (hasPty()) {
      hash = (37 * hash) + PTY_FIELD_NUMBER;
      hash = (53 * hash) + getPty().hashCode();
    }
    if (hasTag()) {
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag().hashCode();
    }
    if (hasStdin()) {
      hash = (37 * hash) + STDIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStdin());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sandbox.process.StartRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.StartRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.StartRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.StartRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.StartRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.StartRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.StartRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.process.StartRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.process.StartRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sandbox.process.StartRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.process.StartRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.process.StartRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sandbox.process.StartRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code process.StartRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:process.StartRequest)
      com.sandbox.process.StartRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.process.ProcessProto.internal_static_process_StartRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.process.ProcessProto.internal_static_process_StartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.process.StartRequest.class, com.sandbox.process.StartRequest.Builder.class);
    }

    // Construct using com.sandbox.process.StartRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProcessFieldBuilder();
        getPtyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      process_ = null;
      if (processBuilder_ != null) {
        processBuilder_.dispose();
        processBuilder_ = null;
      }
      pty_ = null;
      if (ptyBuilder_ != null) {
        ptyBuilder_.dispose();
        ptyBuilder_ = null;
      }
      tag_ = "";
      stdin_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sandbox.process.ProcessProto.internal_static_process_StartRequest_descriptor;
    }

    @java.lang.Override
    public com.sandbox.process.StartRequest getDefaultInstanceForType() {
      return com.sandbox.process.StartRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sandbox.process.StartRequest build() {
      com.sandbox.process.StartRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sandbox.process.StartRequest buildPartial() {
      com.sandbox.process.StartRequest result = new com.sandbox.process.StartRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sandbox.process.StartRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.process_ = processBuilder_ == null
            ? process_
            : processBuilder_.build();
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pty_ = ptyBuilder_ == null
            ? pty_
            : ptyBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tag_ = tag_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.stdin_ = stdin_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sandbox.process.StartRequest) {
        return mergeFrom((com.sandbox.process.StartRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sandbox.process.StartRequest other) {
      if (other == com.sandbox.process.StartRequest.getDefaultInstance()) return this;
      if (other.hasProcess()) {
        mergeProcess(other.getProcess());
      }
      if (other.hasPty()) {
        mergePty(other.getPty());
      }
      if (other.hasTag()) {
        tag_ = other.tag_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasStdin()) {
        setStdin(other.getStdin());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getProcessFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPtyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tag_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              stdin_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.sandbox.process.ProcessConfig process_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.ProcessConfig, com.sandbox.process.ProcessConfig.Builder, com.sandbox.process.ProcessConfigOrBuilder> processBuilder_;
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     * @return Whether the process field is set.
     */
    public boolean hasProcess() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     * @return The process.
     */
    public com.sandbox.process.ProcessConfig getProcess() {
      if (processBuilder_ == null) {
        return process_ == null ? com.sandbox.process.ProcessConfig.getDefaultInstance() : process_;
      } else {
        return processBuilder_.getMessage();
      }
    }
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     */
    public Builder setProcess(com.sandbox.process.ProcessConfig value) {
      if (processBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        process_ = value;
      } else {
        processBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     */
    public Builder setProcess(
        com.sandbox.process.ProcessConfig.Builder builderForValue) {
      if (processBuilder_ == null) {
        process_ = builderForValue.build();
      } else {
        processBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     */
    public Builder mergeProcess(com.sandbox.process.ProcessConfig value) {
      if (processBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          process_ != null &&
          process_ != com.sandbox.process.ProcessConfig.getDefaultInstance()) {
          getProcessBuilder().mergeFrom(value);
        } else {
          process_ = value;
        }
      } else {
        processBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     */
    public Builder clearProcess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      process_ = null;
      if (processBuilder_ != null) {
        processBuilder_.dispose();
        processBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     */
    public com.sandbox.process.ProcessConfig.Builder getProcessBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getProcessFieldBuilder().getBuilder();
    }
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     */
    public com.sandbox.process.ProcessConfigOrBuilder getProcessOrBuilder() {
      if (processBuilder_ != null) {
        return processBuilder_.getMessageOrBuilder();
      } else {
        return process_ == null ?
            com.sandbox.process.ProcessConfig.getDefaultInstance() : process_;
      }
    }
    /**
     * <code>.process.ProcessConfig process = 1 [json_name = "process"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.ProcessConfig, com.sandbox.process.ProcessConfig.Builder, com.sandbox.process.ProcessConfigOrBuilder> 
        getProcessFieldBuilder() {
      if (processBuilder_ == null) {
        processBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.process.ProcessConfig, com.sandbox.process.ProcessConfig.Builder, com.sandbox.process.ProcessConfigOrBuilder>(
                getProcess(),
                getParentForChildren(),
                isClean());
        process_ = null;
      }
      return processBuilder_;
    }

    private com.sandbox.process.PTY pty_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.PTY, com.sandbox.process.PTY.Builder, com.sandbox.process.PTYOrBuilder> ptyBuilder_;
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     * @return Whether the pty field is set.
     */
    public boolean hasPty() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     * @return The pty.
     */
    public com.sandbox.process.PTY getPty() {
      if (ptyBuilder_ == null) {
        return pty_ == null ? com.sandbox.process.PTY.getDefaultInstance() : pty_;
      } else {
        return ptyBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     */
    public Builder setPty(com.sandbox.process.PTY value) {
      if (ptyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pty_ = value;
      } else {
        ptyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     */
    public Builder setPty(
        com.sandbox.process.PTY.Builder builderForValue) {
      if (ptyBuilder_ == null) {
        pty_ = builderForValue.build();
      } else {
        ptyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     */
    public Builder mergePty(com.sandbox.process.PTY value) {
      if (ptyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          pty_ != null &&
          pty_ != com.sandbox.process.PTY.getDefaultInstance()) {
          getPtyBuilder().mergeFrom(value);
        } else {
          pty_ = value;
        }
      } else {
        ptyBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     */
    public Builder clearPty() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pty_ = null;
      if (ptyBuilder_ != null) {
        ptyBuilder_.dispose();
        ptyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     */
    public com.sandbox.process.PTY.Builder getPtyBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPtyFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     */
    public com.sandbox.process.PTYOrBuilder getPtyOrBuilder() {
      if (ptyBuilder_ != null) {
        return ptyBuilder_.getMessageOrBuilder();
      } else {
        return pty_ == null ?
            com.sandbox.process.PTY.getDefaultInstance() : pty_;
      }
    }
    /**
     * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.PTY, com.sandbox.process.PTY.Builder, com.sandbox.process.PTYOrBuilder> 
        getPtyFieldBuilder() {
      if (ptyBuilder_ == null) {
        ptyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.process.PTY, com.sandbox.process.PTY.Builder, com.sandbox.process.PTYOrBuilder>(
                getPty(),
                getParentForChildren(),
                isClean());
        pty_ = null;
      }
      return ptyBuilder_;
    }

    private java.lang.Object tag_ = "";
    /**
     * <code>optional string tag = 3 [json_name = "tag"];</code>
     * @return Whether the tag field is set.
     */
    public boolean hasTag() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string tag = 3 [json_name = "tag"];</code>
     * @return The tag.
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string tag = 3 [json_name = "tag"];</code>
     * @return The bytes for tag.
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string tag = 3 [json_name = "tag"];</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tag_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string tag = 3 [json_name = "tag"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      tag_ = getDefaultInstance().getTag();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string tag = 3 [json_name = "tag"];</code>
     * @param value The bytes for tag to set.
     * @return This builder for chaining.
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tag_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean stdin_ ;
    /**
     * <code>optional bool stdin = 4 [json_name = "stdin"];</code>
     * @return Whether the stdin field is set.
     */
    @java.lang.Override
    public boolean hasStdin() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool stdin = 4 [json_name = "stdin"];</code>
     * @return The stdin.
     */
    @java.lang.Override
    public boolean getStdin() {
      return stdin_;
    }
    /**
     * <code>optional bool stdin = 4 [json_name = "stdin"];</code>
     * @param value The stdin to set.
     * @return This builder for chaining.
     */
    public Builder setStdin(boolean value) {
      
      stdin_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool stdin = 4 [json_name = "stdin"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStdin() {
      bitField0_ = (bitField0_ & ~0x00000008);
      stdin_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:process.StartRequest)
  }

  // @@protoc_insertion_point(class_scope:process.StartRequest)
  private static final com.sandbox.process.StartRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sandbox.process.StartRequest();
  }

  public static com.sandbox.process.StartRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StartRequest>
      PARSER = new com.google.protobuf.AbstractParser<StartRequest>() {
    @java.lang.Override
    public StartRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StartRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StartRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sandbox.process.StartRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

