// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

/**
 * Protobuf type {@code process.StreamInputRequest}
 */
public final class StreamInputRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:process.StreamInputRequest)
    StreamInputRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamInputRequest.newBuilder() to construct.
  private StreamInputRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamInputRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamInputRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sandbox.process.StreamInputRequest.class, com.sandbox.process.StreamInputRequest.Builder.class);
  }

  public interface StartEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process.StreamInputRequest.StartEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     * @return Whether the process field is set.
     */
    boolean hasProcess();
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     * @return The process.
     */
    com.sandbox.process.ProcessSelector getProcess();
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder();
  }
  /**
   * Protobuf type {@code process.StreamInputRequest.StartEvent}
   */
  public static final class StartEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:process.StreamInputRequest.StartEvent)
      StartEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StartEvent.newBuilder() to construct.
    private StartEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StartEvent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StartEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_StartEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_StartEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.process.StreamInputRequest.StartEvent.class, com.sandbox.process.StreamInputRequest.StartEvent.Builder.class);
    }

    public static final int PROCESS_FIELD_NUMBER = 1;
    private com.sandbox.process.ProcessSelector process_;
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     * @return Whether the process field is set.
     */
    @java.lang.Override
    public boolean hasProcess() {
      return process_ != null;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     * @return The process.
     */
    @java.lang.Override
    public com.sandbox.process.ProcessSelector getProcess() {
      return process_ == null ? com.sandbox.process.ProcessSelector.getDefaultInstance() : process_;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    @java.lang.Override
    public com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder() {
      return process_ == null ? com.sandbox.process.ProcessSelector.getDefaultInstance() : process_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (process_ != null) {
        output.writeMessage(1, getProcess());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (process_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProcess());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sandbox.process.StreamInputRequest.StartEvent)) {
        return super.equals(obj);
      }
      com.sandbox.process.StreamInputRequest.StartEvent other = (com.sandbox.process.StreamInputRequest.StartEvent) obj;

      if (hasProcess() != other.hasProcess()) return false;
      if (hasProcess()) {
        if (!getProcess()
            .equals(other.getProcess())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProcess()) {
        hash = (37 * hash) + PROCESS_FIELD_NUMBER;
        hash = (53 * hash) + getProcess().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.StartEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sandbox.process.StreamInputRequest.StartEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process.StreamInputRequest.StartEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process.StreamInputRequest.StartEvent)
        com.sandbox.process.StreamInputRequest.StartEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_StartEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_StartEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sandbox.process.StreamInputRequest.StartEvent.class, com.sandbox.process.StreamInputRequest.StartEvent.Builder.class);
      }

      // Construct using com.sandbox.process.StreamInputRequest.StartEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        process_ = null;
        if (processBuilder_ != null) {
          processBuilder_.dispose();
          processBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_StartEvent_descriptor;
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.StartEvent getDefaultInstanceForType() {
        return com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.StartEvent build() {
        com.sandbox.process.StreamInputRequest.StartEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.StartEvent buildPartial() {
        com.sandbox.process.StreamInputRequest.StartEvent result = new com.sandbox.process.StreamInputRequest.StartEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.sandbox.process.StreamInputRequest.StartEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.process_ = processBuilder_ == null
              ? process_
              : processBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sandbox.process.StreamInputRequest.StartEvent) {
          return mergeFrom((com.sandbox.process.StreamInputRequest.StartEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sandbox.process.StreamInputRequest.StartEvent other) {
        if (other == com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance()) return this;
        if (other.hasProcess()) {
          mergeProcess(other.getProcess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getProcessFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.sandbox.process.ProcessSelector process_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sandbox.process.ProcessSelector, com.sandbox.process.ProcessSelector.Builder, com.sandbox.process.ProcessSelectorOrBuilder> processBuilder_;
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       * @return Whether the process field is set.
       */
      public boolean hasProcess() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       * @return The process.
       */
      public com.sandbox.process.ProcessSelector getProcess() {
        if (processBuilder_ == null) {
          return process_ == null ? com.sandbox.process.ProcessSelector.getDefaultInstance() : process_;
        } else {
          return processBuilder_.getMessage();
        }
      }
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       */
      public Builder setProcess(com.sandbox.process.ProcessSelector value) {
        if (processBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          process_ = value;
        } else {
          processBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       */
      public Builder setProcess(
          com.sandbox.process.ProcessSelector.Builder builderForValue) {
        if (processBuilder_ == null) {
          process_ = builderForValue.build();
        } else {
          processBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       */
      public Builder mergeProcess(com.sandbox.process.ProcessSelector value) {
        if (processBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            process_ != null &&
            process_ != com.sandbox.process.ProcessSelector.getDefaultInstance()) {
            getProcessBuilder().mergeFrom(value);
          } else {
            process_ = value;
          }
        } else {
          processBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       */
      public Builder clearProcess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        process_ = null;
        if (processBuilder_ != null) {
          processBuilder_.dispose();
          processBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       */
      public com.sandbox.process.ProcessSelector.Builder getProcessBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getProcessFieldBuilder().getBuilder();
      }
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       */
      public com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder() {
        if (processBuilder_ != null) {
          return processBuilder_.getMessageOrBuilder();
        } else {
          return process_ == null ?
              com.sandbox.process.ProcessSelector.getDefaultInstance() : process_;
        }
      }
      /**
       * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sandbox.process.ProcessSelector, com.sandbox.process.ProcessSelector.Builder, com.sandbox.process.ProcessSelectorOrBuilder> 
          getProcessFieldBuilder() {
        if (processBuilder_ == null) {
          processBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sandbox.process.ProcessSelector, com.sandbox.process.ProcessSelector.Builder, com.sandbox.process.ProcessSelectorOrBuilder>(
                  getProcess(),
                  getParentForChildren(),
                  isClean());
          process_ = null;
        }
        return processBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:process.StreamInputRequest.StartEvent)
    }

    // @@protoc_insertion_point(class_scope:process.StreamInputRequest.StartEvent)
    private static final com.sandbox.process.StreamInputRequest.StartEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sandbox.process.StreamInputRequest.StartEvent();
    }

    public static com.sandbox.process.StreamInputRequest.StartEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StartEvent>
        PARSER = new com.google.protobuf.AbstractParser<StartEvent>() {
      @java.lang.Override
      public StartEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StartEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StartEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.StartEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process.StreamInputRequest.DataEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
     * @return Whether the input field is set.
     */
    boolean hasInput();
    /**
     * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
     * @return The input.
     */
    com.sandbox.process.ProcessInput getInput();
    /**
     * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
     */
    com.sandbox.process.ProcessInputOrBuilder getInputOrBuilder();
  }
  /**
   * Protobuf type {@code process.StreamInputRequest.DataEvent}
   */
  public static final class DataEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:process.StreamInputRequest.DataEvent)
      DataEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataEvent.newBuilder() to construct.
    private DataEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataEvent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_DataEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_DataEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.process.StreamInputRequest.DataEvent.class, com.sandbox.process.StreamInputRequest.DataEvent.Builder.class);
    }

    public static final int INPUT_FIELD_NUMBER = 2;
    private com.sandbox.process.ProcessInput input_;
    /**
     * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
     * @return Whether the input field is set.
     */
    @java.lang.Override
    public boolean hasInput() {
      return input_ != null;
    }
    /**
     * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
     * @return The input.
     */
    @java.lang.Override
    public com.sandbox.process.ProcessInput getInput() {
      return input_ == null ? com.sandbox.process.ProcessInput.getDefaultInstance() : input_;
    }
    /**
     * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
     */
    @java.lang.Override
    public com.sandbox.process.ProcessInputOrBuilder getInputOrBuilder() {
      return input_ == null ? com.sandbox.process.ProcessInput.getDefaultInstance() : input_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (input_ != null) {
        output.writeMessage(2, getInput());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (input_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getInput());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sandbox.process.StreamInputRequest.DataEvent)) {
        return super.equals(obj);
      }
      com.sandbox.process.StreamInputRequest.DataEvent other = (com.sandbox.process.StreamInputRequest.DataEvent) obj;

      if (hasInput() != other.hasInput()) return false;
      if (hasInput()) {
        if (!getInput()
            .equals(other.getInput())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInput()) {
        hash = (37 * hash) + INPUT_FIELD_NUMBER;
        hash = (53 * hash) + getInput().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.DataEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sandbox.process.StreamInputRequest.DataEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process.StreamInputRequest.DataEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process.StreamInputRequest.DataEvent)
        com.sandbox.process.StreamInputRequest.DataEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_DataEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_DataEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sandbox.process.StreamInputRequest.DataEvent.class, com.sandbox.process.StreamInputRequest.DataEvent.Builder.class);
      }

      // Construct using com.sandbox.process.StreamInputRequest.DataEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        input_ = null;
        if (inputBuilder_ != null) {
          inputBuilder_.dispose();
          inputBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_DataEvent_descriptor;
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.DataEvent getDefaultInstanceForType() {
        return com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.DataEvent build() {
        com.sandbox.process.StreamInputRequest.DataEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.DataEvent buildPartial() {
        com.sandbox.process.StreamInputRequest.DataEvent result = new com.sandbox.process.StreamInputRequest.DataEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.sandbox.process.StreamInputRequest.DataEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.input_ = inputBuilder_ == null
              ? input_
              : inputBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sandbox.process.StreamInputRequest.DataEvent) {
          return mergeFrom((com.sandbox.process.StreamInputRequest.DataEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sandbox.process.StreamInputRequest.DataEvent other) {
        if (other == com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance()) return this;
        if (other.hasInput()) {
          mergeInput(other.getInput());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                input.readMessage(
                    getInputFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.sandbox.process.ProcessInput input_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sandbox.process.ProcessInput, com.sandbox.process.ProcessInput.Builder, com.sandbox.process.ProcessInputOrBuilder> inputBuilder_;
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       * @return Whether the input field is set.
       */
      public boolean hasInput() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       * @return The input.
       */
      public com.sandbox.process.ProcessInput getInput() {
        if (inputBuilder_ == null) {
          return input_ == null ? com.sandbox.process.ProcessInput.getDefaultInstance() : input_;
        } else {
          return inputBuilder_.getMessage();
        }
      }
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       */
      public Builder setInput(com.sandbox.process.ProcessInput value) {
        if (inputBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          input_ = value;
        } else {
          inputBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       */
      public Builder setInput(
          com.sandbox.process.ProcessInput.Builder builderForValue) {
        if (inputBuilder_ == null) {
          input_ = builderForValue.build();
        } else {
          inputBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       */
      public Builder mergeInput(com.sandbox.process.ProcessInput value) {
        if (inputBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            input_ != null &&
            input_ != com.sandbox.process.ProcessInput.getDefaultInstance()) {
            getInputBuilder().mergeFrom(value);
          } else {
            input_ = value;
          }
        } else {
          inputBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       */
      public Builder clearInput() {
        bitField0_ = (bitField0_ & ~0x00000001);
        input_ = null;
        if (inputBuilder_ != null) {
          inputBuilder_.dispose();
          inputBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       */
      public com.sandbox.process.ProcessInput.Builder getInputBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInputFieldBuilder().getBuilder();
      }
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       */
      public com.sandbox.process.ProcessInputOrBuilder getInputOrBuilder() {
        if (inputBuilder_ != null) {
          return inputBuilder_.getMessageOrBuilder();
        } else {
          return input_ == null ?
              com.sandbox.process.ProcessInput.getDefaultInstance() : input_;
        }
      }
      /**
       * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sandbox.process.ProcessInput, com.sandbox.process.ProcessInput.Builder, com.sandbox.process.ProcessInputOrBuilder> 
          getInputFieldBuilder() {
        if (inputBuilder_ == null) {
          inputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sandbox.process.ProcessInput, com.sandbox.process.ProcessInput.Builder, com.sandbox.process.ProcessInputOrBuilder>(
                  getInput(),
                  getParentForChildren(),
                  isClean());
          input_ = null;
        }
        return inputBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:process.StreamInputRequest.DataEvent)
    }

    // @@protoc_insertion_point(class_scope:process.StreamInputRequest.DataEvent)
    private static final com.sandbox.process.StreamInputRequest.DataEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sandbox.process.StreamInputRequest.DataEvent();
    }

    public static com.sandbox.process.StreamInputRequest.DataEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataEvent>
        PARSER = new com.google.protobuf.AbstractParser<DataEvent>() {
      @java.lang.Override
      public DataEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.DataEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeepAliveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process.StreamInputRequest.KeepAlive)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code process.StreamInputRequest.KeepAlive}
   */
  public static final class KeepAlive extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:process.StreamInputRequest.KeepAlive)
      KeepAliveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KeepAlive.newBuilder() to construct.
    private KeepAlive(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeepAlive() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KeepAlive();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_KeepAlive_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_KeepAlive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.process.StreamInputRequest.KeepAlive.class, com.sandbox.process.StreamInputRequest.KeepAlive.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sandbox.process.StreamInputRequest.KeepAlive)) {
        return super.equals(obj);
      }
      com.sandbox.process.StreamInputRequest.KeepAlive other = (com.sandbox.process.StreamInputRequest.KeepAlive) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sandbox.process.StreamInputRequest.KeepAlive parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sandbox.process.StreamInputRequest.KeepAlive prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process.StreamInputRequest.KeepAlive}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process.StreamInputRequest.KeepAlive)
        com.sandbox.process.StreamInputRequest.KeepAliveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_KeepAlive_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_KeepAlive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sandbox.process.StreamInputRequest.KeepAlive.class, com.sandbox.process.StreamInputRequest.KeepAlive.Builder.class);
      }

      // Construct using com.sandbox.process.StreamInputRequest.KeepAlive.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_KeepAlive_descriptor;
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.KeepAlive getDefaultInstanceForType() {
        return com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance();
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.KeepAlive build() {
        com.sandbox.process.StreamInputRequest.KeepAlive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sandbox.process.StreamInputRequest.KeepAlive buildPartial() {
        com.sandbox.process.StreamInputRequest.KeepAlive result = new com.sandbox.process.StreamInputRequest.KeepAlive(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sandbox.process.StreamInputRequest.KeepAlive) {
          return mergeFrom((com.sandbox.process.StreamInputRequest.KeepAlive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sandbox.process.StreamInputRequest.KeepAlive other) {
        if (other == com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:process.StreamInputRequest.KeepAlive)
    }

    // @@protoc_insertion_point(class_scope:process.StreamInputRequest.KeepAlive)
    private static final com.sandbox.process.StreamInputRequest.KeepAlive DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sandbox.process.StreamInputRequest.KeepAlive();
    }

    public static com.sandbox.process.StreamInputRequest.KeepAlive getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeepAlive>
        PARSER = new com.google.protobuf.AbstractParser<KeepAlive>() {
      @java.lang.Override
      public KeepAlive parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KeepAlive> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeepAlive> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.KeepAlive getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int eventCase_ = 0;
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    START(1),
    DATA(2),
    KEEPALIVE(3),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 1: return START;
        case 2: return DATA;
        case 3: return KEEPALIVE;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int START_FIELD_NUMBER = 1;
  /**
   * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
   * @return Whether the start field is set.
   */
  @java.lang.Override
  public boolean hasStart() {
    return eventCase_ == 1;
  }
  /**
   * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
   * @return The start.
   */
  @java.lang.Override
  public com.sandbox.process.StreamInputRequest.StartEvent getStart() {
    if (eventCase_ == 1) {
       return (com.sandbox.process.StreamInputRequest.StartEvent) event_;
    }
    return com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance();
  }
  /**
   * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
   */
  @java.lang.Override
  public com.sandbox.process.StreamInputRequest.StartEventOrBuilder getStartOrBuilder() {
    if (eventCase_ == 1) {
       return (com.sandbox.process.StreamInputRequest.StartEvent) event_;
    }
    return com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance();
  }

  public static final int DATA_FIELD_NUMBER = 2;
  /**
   * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return eventCase_ == 2;
  }
  /**
   * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
   * @return The data.
   */
  @java.lang.Override
  public com.sandbox.process.StreamInputRequest.DataEvent getData() {
    if (eventCase_ == 2) {
       return (com.sandbox.process.StreamInputRequest.DataEvent) event_;
    }
    return com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance();
  }
  /**
   * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
   */
  @java.lang.Override
  public com.sandbox.process.StreamInputRequest.DataEventOrBuilder getDataOrBuilder() {
    if (eventCase_ == 2) {
       return (com.sandbox.process.StreamInputRequest.DataEvent) event_;
    }
    return com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance();
  }

  public static final int KEEPALIVE_FIELD_NUMBER = 3;
  /**
   * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   * @return Whether the keepalive field is set.
   */
  @java.lang.Override
  public boolean hasKeepalive() {
    return eventCase_ == 3;
  }
  /**
   * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   * @return The keepalive.
   */
  @java.lang.Override
  public com.sandbox.process.StreamInputRequest.KeepAlive getKeepalive() {
    if (eventCase_ == 3) {
       return (com.sandbox.process.StreamInputRequest.KeepAlive) event_;
    }
    return com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance();
  }
  /**
   * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   */
  @java.lang.Override
  public com.sandbox.process.StreamInputRequest.KeepAliveOrBuilder getKeepaliveOrBuilder() {
    if (eventCase_ == 3) {
       return (com.sandbox.process.StreamInputRequest.KeepAlive) event_;
    }
    return com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 1) {
      output.writeMessage(1, (com.sandbox.process.StreamInputRequest.StartEvent) event_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (com.sandbox.process.StreamInputRequest.DataEvent) event_);
    }
    if (eventCase_ == 3) {
      output.writeMessage(3, (com.sandbox.process.StreamInputRequest.KeepAlive) event_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.sandbox.process.StreamInputRequest.StartEvent) event_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.sandbox.process.StreamInputRequest.DataEvent) event_);
    }
    if (eventCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.sandbox.process.StreamInputRequest.KeepAlive) event_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sandbox.process.StreamInputRequest)) {
      return super.equals(obj);
    }
    com.sandbox.process.StreamInputRequest other = (com.sandbox.process.StreamInputRequest) obj;

    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 1:
        if (!getStart()
            .equals(other.getStart())) return false;
        break;
      case 2:
        if (!getData()
            .equals(other.getData())) return false;
        break;
      case 3:
        if (!getKeepalive()
            .equals(other.getKeepalive())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (eventCase_) {
      case 1:
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
        break;
      case 2:
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        break;
      case 3:
        hash = (37 * hash) + KEEPALIVE_FIELD_NUMBER;
        hash = (53 * hash) + getKeepalive().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sandbox.process.StreamInputRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.process.StreamInputRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sandbox.process.StreamInputRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sandbox.process.StreamInputRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sandbox.process.StreamInputRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code process.StreamInputRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:process.StreamInputRequest)
      com.sandbox.process.StreamInputRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sandbox.process.StreamInputRequest.class, com.sandbox.process.StreamInputRequest.Builder.class);
    }

    // Construct using com.sandbox.process.StreamInputRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (startBuilder_ != null) {
        startBuilder_.clear();
      }
      if (dataBuilder_ != null) {
        dataBuilder_.clear();
      }
      if (keepaliveBuilder_ != null) {
        keepaliveBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sandbox.process.ProcessProto.internal_static_process_StreamInputRequest_descriptor;
    }

    @java.lang.Override
    public com.sandbox.process.StreamInputRequest getDefaultInstanceForType() {
      return com.sandbox.process.StreamInputRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sandbox.process.StreamInputRequest build() {
      com.sandbox.process.StreamInputRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sandbox.process.StreamInputRequest buildPartial() {
      com.sandbox.process.StreamInputRequest result = new com.sandbox.process.StreamInputRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sandbox.process.StreamInputRequest result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.sandbox.process.StreamInputRequest result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 1 &&
          startBuilder_ != null) {
        result.event_ = startBuilder_.build();
      }
      if (eventCase_ == 2 &&
          dataBuilder_ != null) {
        result.event_ = dataBuilder_.build();
      }
      if (eventCase_ == 3 &&
          keepaliveBuilder_ != null) {
        result.event_ = keepaliveBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sandbox.process.StreamInputRequest) {
        return mergeFrom((com.sandbox.process.StreamInputRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sandbox.process.StreamInputRequest other) {
      if (other == com.sandbox.process.StreamInputRequest.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case START: {
          mergeStart(other.getStart());
          break;
        }
        case DATA: {
          mergeData(other.getData());
          break;
        }
        case KEEPALIVE: {
          mergeKeepalive(other.getKeepalive());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStartFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getKeepaliveFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.StreamInputRequest.StartEvent, com.sandbox.process.StreamInputRequest.StartEvent.Builder, com.sandbox.process.StreamInputRequest.StartEventOrBuilder> startBuilder_;
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return eventCase_ == 1;
    }
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     * @return The start.
     */
    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.StartEvent getStart() {
      if (startBuilder_ == null) {
        if (eventCase_ == 1) {
          return (com.sandbox.process.StreamInputRequest.StartEvent) event_;
        }
        return com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 1) {
          return startBuilder_.getMessage();
        }
        return com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     */
    public Builder setStart(com.sandbox.process.StreamInputRequest.StartEvent value) {
      if (startBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        startBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     */
    public Builder setStart(
        com.sandbox.process.StreamInputRequest.StartEvent.Builder builderForValue) {
      if (startBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        startBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     */
    public Builder mergeStart(com.sandbox.process.StreamInputRequest.StartEvent value) {
      if (startBuilder_ == null) {
        if (eventCase_ == 1 &&
            event_ != com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance()) {
          event_ = com.sandbox.process.StreamInputRequest.StartEvent.newBuilder((com.sandbox.process.StreamInputRequest.StartEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 1) {
          startBuilder_.mergeFrom(value);
        } else {
          startBuilder_.setMessage(value);
        }
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     */
    public Builder clearStart() {
      if (startBuilder_ == null) {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
        }
        startBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     */
    public com.sandbox.process.StreamInputRequest.StartEvent.Builder getStartBuilder() {
      return getStartFieldBuilder().getBuilder();
    }
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     */
    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.StartEventOrBuilder getStartOrBuilder() {
      if ((eventCase_ == 1) && (startBuilder_ != null)) {
        return startBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 1) {
          return (com.sandbox.process.StreamInputRequest.StartEvent) event_;
        }
        return com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.StreamInputRequest.StartEvent, com.sandbox.process.StreamInputRequest.StartEvent.Builder, com.sandbox.process.StreamInputRequest.StartEventOrBuilder> 
        getStartFieldBuilder() {
      if (startBuilder_ == null) {
        if (!(eventCase_ == 1)) {
          event_ = com.sandbox.process.StreamInputRequest.StartEvent.getDefaultInstance();
        }
        startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.process.StreamInputRequest.StartEvent, com.sandbox.process.StreamInputRequest.StartEvent.Builder, com.sandbox.process.StreamInputRequest.StartEventOrBuilder>(
                (com.sandbox.process.StreamInputRequest.StartEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 1;
      onChanged();
      return startBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.StreamInputRequest.DataEvent, com.sandbox.process.StreamInputRequest.DataEvent.Builder, com.sandbox.process.StreamInputRequest.DataEventOrBuilder> dataBuilder_;
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return eventCase_ == 2;
    }
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     * @return The data.
     */
    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.DataEvent getData() {
      if (dataBuilder_ == null) {
        if (eventCase_ == 2) {
          return (com.sandbox.process.StreamInputRequest.DataEvent) event_;
        }
        return com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return dataBuilder_.getMessage();
        }
        return com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     */
    public Builder setData(com.sandbox.process.StreamInputRequest.DataEvent value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     */
    public Builder setData(
        com.sandbox.process.StreamInputRequest.DataEvent.Builder builderForValue) {
      if (dataBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     */
    public Builder mergeData(com.sandbox.process.StreamInputRequest.DataEvent value) {
      if (dataBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance()) {
          event_ = com.sandbox.process.StreamInputRequest.DataEvent.newBuilder((com.sandbox.process.StreamInputRequest.DataEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          dataBuilder_.mergeFrom(value);
        } else {
          dataBuilder_.setMessage(value);
        }
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     */
    public com.sandbox.process.StreamInputRequest.DataEvent.Builder getDataBuilder() {
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     */
    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.DataEventOrBuilder getDataOrBuilder() {
      if ((eventCase_ == 2) && (dataBuilder_ != null)) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (com.sandbox.process.StreamInputRequest.DataEvent) event_;
        }
        return com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.StreamInputRequest.DataEvent, com.sandbox.process.StreamInputRequest.DataEvent.Builder, com.sandbox.process.StreamInputRequest.DataEventOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = com.sandbox.process.StreamInputRequest.DataEvent.getDefaultInstance();
        }
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.process.StreamInputRequest.DataEvent, com.sandbox.process.StreamInputRequest.DataEvent.Builder, com.sandbox.process.StreamInputRequest.DataEventOrBuilder>(
                (com.sandbox.process.StreamInputRequest.DataEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();
      return dataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.StreamInputRequest.KeepAlive, com.sandbox.process.StreamInputRequest.KeepAlive.Builder, com.sandbox.process.StreamInputRequest.KeepAliveOrBuilder> keepaliveBuilder_;
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     * @return Whether the keepalive field is set.
     */
    @java.lang.Override
    public boolean hasKeepalive() {
      return eventCase_ == 3;
    }
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     * @return The keepalive.
     */
    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.KeepAlive getKeepalive() {
      if (keepaliveBuilder_ == null) {
        if (eventCase_ == 3) {
          return (com.sandbox.process.StreamInputRequest.KeepAlive) event_;
        }
        return com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance();
      } else {
        if (eventCase_ == 3) {
          return keepaliveBuilder_.getMessage();
        }
        return com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance();
      }
    }
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public Builder setKeepalive(com.sandbox.process.StreamInputRequest.KeepAlive value) {
      if (keepaliveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        keepaliveBuilder_.setMessage(value);
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public Builder setKeepalive(
        com.sandbox.process.StreamInputRequest.KeepAlive.Builder builderForValue) {
      if (keepaliveBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        keepaliveBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public Builder mergeKeepalive(com.sandbox.process.StreamInputRequest.KeepAlive value) {
      if (keepaliveBuilder_ == null) {
        if (eventCase_ == 3 &&
            event_ != com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance()) {
          event_ = com.sandbox.process.StreamInputRequest.KeepAlive.newBuilder((com.sandbox.process.StreamInputRequest.KeepAlive) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 3) {
          keepaliveBuilder_.mergeFrom(value);
        } else {
          keepaliveBuilder_.setMessage(value);
        }
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public Builder clearKeepalive() {
      if (keepaliveBuilder_ == null) {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
        }
        keepaliveBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    public com.sandbox.process.StreamInputRequest.KeepAlive.Builder getKeepaliveBuilder() {
      return getKeepaliveFieldBuilder().getBuilder();
    }
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    @java.lang.Override
    public com.sandbox.process.StreamInputRequest.KeepAliveOrBuilder getKeepaliveOrBuilder() {
      if ((eventCase_ == 3) && (keepaliveBuilder_ != null)) {
        return keepaliveBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 3) {
          return (com.sandbox.process.StreamInputRequest.KeepAlive) event_;
        }
        return com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance();
      }
    }
    /**
     * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sandbox.process.StreamInputRequest.KeepAlive, com.sandbox.process.StreamInputRequest.KeepAlive.Builder, com.sandbox.process.StreamInputRequest.KeepAliveOrBuilder> 
        getKeepaliveFieldBuilder() {
      if (keepaliveBuilder_ == null) {
        if (!(eventCase_ == 3)) {
          event_ = com.sandbox.process.StreamInputRequest.KeepAlive.getDefaultInstance();
        }
        keepaliveBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sandbox.process.StreamInputRequest.KeepAlive, com.sandbox.process.StreamInputRequest.KeepAlive.Builder, com.sandbox.process.StreamInputRequest.KeepAliveOrBuilder>(
                (com.sandbox.process.StreamInputRequest.KeepAlive) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 3;
      onChanged();
      return keepaliveBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:process.StreamInputRequest)
  }

  // @@protoc_insertion_point(class_scope:process.StreamInputRequest)
  private static final com.sandbox.process.StreamInputRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sandbox.process.StreamInputRequest();
  }

  public static com.sandbox.process.StreamInputRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamInputRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamInputRequest>() {
    @java.lang.Override
    public StreamInputRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamInputRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamInputRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sandbox.process.StreamInputRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

