// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process/process.proto

package com.sandbox.process;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  boolean hasProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  com.sandbox.process.ProcessSelector getProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   */
  com.sandbox.process.ProcessSelectorOrBuilder getProcessOrBuilder();

  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   * @return Whether the pty field is set.
   */
  boolean hasPty();
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   * @return The pty.
   */
  com.sandbox.process.PTY getPty();
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   */
  com.sandbox.process.PTYOrBuilder getPtyOrBuilder();
}
